In [6]:
import numpy as np
array = np.array([[1,2,3,4],[5,6,7,8]])
print(array)
print(array.tolist())

[[1 2 3 4]
 [5 6 7 8]]
[[1, 2, 3, 4], [5, 6, 7, 8]]


In [48]:
import numpy as np
ar = np.array([[1,2,3],[5,6,7],[3,4,12]])
a = np.trace(ar)

def sum_diag(ar):
    result=0
    for i in range(0,len(ar)):
        result=result+ar[i,i]
    return result
b=sum_diag(ar)
print(a)
print(b)

19
19


In [68]:
import numpy as np
def test_array(x,ar):
    result=[]
    print("les élements de la matrice supérieurs à {} sont :".format(x))
    for i in np.nditer(ar):
        if i>x:
            print(i,end=' ')     
    return
x=5
ar = np.array([[1,2,3],[5,6,7],[3,4,12]])
test_array(x,ar)

les élements de la matrice supérieurs à 5 sont :
6 7 12 

In [84]:
import numpy as np
a = np.array([[1,2,3],[5,6,7],[3,4,12],[3,4,12]])
b = np.array([[3,4,4],[15,46,57],[63,44,32],[3,4,12]])
result=[]
nb_row=a.shape[0]
nb_column=a.shape[1]
for i in range(0,nb_row):
    for j in range(0,nb_column):
        result.append(a[i,j]+b[i,j])
c=np.array(result).reshape(nb_row,nb_column)
print(c)

[[ 4  6  7]
 [20 52 64]
 [66 48 44]
 [ 6  8 24]]


In [85]:
import numpy as np
def subtract(ar):
    result=0
    mean_ar=np.mean(ar,axis=1)
    print(mean_ar)
    for i in np.nditer(mean_ar):
        result=result+i
    return result
a = np.array([[1,2,1],[5,6,7],[3,2,12],[3,45,12]])
subtract(a)

[ 1.33333333  6.          5.66666667 20.        ]


33.0