In [1]:
a =[]
def mult(x,y):
    for i in range(x,y+1):
        if i%7==0 and i%5!=0:
            a.append(i)
    return a
x=2000
y=3200
mult(x,y)

[2002,
 2009,
 2016,
 2023,
 2037,
 2044,
 2051,
 2058,
 2072,
 2079,
 2086,
 2093,
 2107,
 2114,
 2121,
 2128,
 2142,
 2149,
 2156,
 2163,
 2177,
 2184,
 2191,
 2198,
 2212,
 2219,
 2226,
 2233,
 2247,
 2254,
 2261,
 2268,
 2282,
 2289,
 2296,
 2303,
 2317,
 2324,
 2331,
 2338,
 2352,
 2359,
 2366,
 2373,
 2387,
 2394,
 2401,
 2408,
 2422,
 2429,
 2436,
 2443,
 2457,
 2464,
 2471,
 2478,
 2492,
 2499,
 2506,
 2513,
 2527,
 2534,
 2541,
 2548,
 2562,
 2569,
 2576,
 2583,
 2597,
 2604,
 2611,
 2618,
 2632,
 2639,
 2646,
 2653,
 2667,
 2674,
 2681,
 2688,
 2702,
 2709,
 2716,
 2723,
 2737,
 2744,
 2751,
 2758,
 2772,
 2779,
 2786,
 2793,
 2807,
 2814,
 2821,
 2828,
 2842,
 2849,
 2856,
 2863,
 2877,
 2884,
 2891,
 2898,
 2912,
 2919,
 2926,
 2933,
 2947,
 2954,
 2961,
 2968,
 2982,
 2989,
 2996,
 3003,
 3017,
 3024,
 3031,
 3038,
 3052,
 3059,
 3066,
 3073,
 3087,
 3094,
 3101,
 3108,
 3122,
 3129,
 3136,
 3143,
 3157,
 3164,
 3171,
 3178,
 3192,
 3199]

In [2]:
def fact(x):
    if x==0:
        return 1
    else:
        a=1
        for i in range(x,1,-1):
            a=a*i
    return a

x=5
fact(x)
    

120

In [3]:
def dict_gen(n):
    Mydict=dict()
    for i in range (1,n+1):
        Mydict[i]=i*i
    return Mydict
n=8
dict_gen(n)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}

In [4]:
def missing_char(string,n):
    list_srt=list(string)
    if len(string)<=n:
        print("L'indice demandé est plus grand que le nombre de lettre de votre mot")
    else:
        del list_srt[n]   
        return ''.join(list_srt)
    
string ='kitten'
n=1
missing_char(string,n)


'ktten'

In [5]:
import numpy as np
My_array=np.array([[0,1],[2,3],[4,5]])
print(My_array)
My_array.tolist()

[[0 1]
 [2 3]
 [4 5]]


[[0, 1], [2, 3], [4, 5]]

In [6]:
import numpy as np
array_1=np.array([0,1,2])
array_2=np.array([2,1,0])
print(array_1)
print(array_2)
array=np.stack((array_1,array_2))
np.cov(array)

[0 1 2]
[2 1 0]


array([[ 1., -1.],
       [-1.,  1.]])

In [8]:
from math import *
def calcul(d):
    c=50
    h=30
    Out=[]
    
    In=d.split(',')
    for i in range(len(In)):
       Out.append(round(sqrt((2*c*int(In[i])/h))))
    return Out
d=input('Insérez vos valeurs séparées par une "," :')
calcul(d)

Insérez vos valeurs séparées par une "," :100,150,180


[18, 22, 24]